### ISSUE TITLE
Signing Key is Public

### ISSUE THREAD

**Issue by aphix** [j-f1/dotfiles#1]
Not sure if you want this to be publicly available.

https://github.com/j-f1/dotfiles/blob/feaf4a5c7b286293ae09bad202bf63cb2919e75f/.gitconfig#L4

Sorry if it's not a problem, just looking out for you. Feel free to close.

Cheers,
Aphix

**Comment by j-f1** [comment]
Thanks for opening this! This is just the ID for my key, not the actual key itself. It’s public elsewhere on the Internet, too: https://keybase.io/j_f
